"""empty message

Revision ID: 023087145dbe
Revises: fbed2214b9c6
Create Date: 2022-07-05 18:08:19.591825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '023087145dbe'
down_revision = 'fbed2214b9c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
