"""empty message

Revision ID: 058f346b8cd3
Revises: 08b7bca09875
Create Date: 2022-07-04 11:00:53.070232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '058f346b8cd3'
down_revision = '08b7bca09875'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
