"""empty message

Revision ID: 0cf7dece3fe5
Revises: 5d6ef025b8ea
Create Date: 2022-07-04 13:07:45.030224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cf7dece3fe5'
down_revision = '5d6ef025b8ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
