"""empty message

Revision ID: 2ac9fbc21282
Revises: 77308066e06c
Create Date: 2022-07-04 12:42:54.567270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ac9fbc21282'
down_revision = '77308066e06c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
