"""empty message

Revision ID: 300d580bda3e
Revises: 6381a0554926
Create Date: 2022-07-06 11:31:07.776614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '300d580bda3e'
down_revision = '6381a0554926'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
