"""empty message

Revision ID: 3a5df5e96c7f
Revises: 218329e30de9
Create Date: 2022-07-06 12:58:18.980721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a5df5e96c7f'
down_revision = '218329e30de9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
