"""empty message

Revision ID: 507355f5ac94
Revises: 97db2b087b49
Create Date: 2022-07-07 09:56:26.391018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '507355f5ac94'
down_revision = '97db2b087b49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
