"""empty message

Revision ID: 5d6ef025b8ea
Revises: 8d83bdf996ad
Create Date: 2022-07-04 13:05:52.933918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d6ef025b8ea'
down_revision = '8d83bdf996ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
