"""empty message

Revision ID: 622564c9d40b
Revises: cf67c17ca4d5
Create Date: 2022-07-06 18:24:15.843827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '622564c9d40b'
down_revision = 'cf67c17ca4d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home_user', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('home_user_room_id_fkey', 'home_user', type_='foreignkey')
    op.create_foreign_key(None, 'home_user', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('home_user', 'room_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home_user', sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'home_user', type_='foreignkey')
    op.create_foreign_key('home_user_room_id_fkey', 'home_user', 'room', ['room_id'], ['id'], ondelete='CASCADE')
    op.drop_column('home_user', 'user_id')
    # ### end Alembic commands ###
