"""empty message

Revision ID: 74b7ba77d199
Revises: 622564c9d40b
Create Date: 2022-07-06 18:54:34.615788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74b7ba77d199'
down_revision = '622564c9d40b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
