"""empty message

Revision ID: 77308066e06c
Revises: 058f346b8cd3
Create Date: 2022-07-04 11:02:18.953550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77308066e06c'
down_revision = '058f346b8cd3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('home')
    # ### end Alembic commands ###
