"""empty message

Revision ID: 790e406ef4b1
Revises: d8f502d5beec
Create Date: 2022-07-06 12:46:06.391619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '790e406ef4b1'
down_revision = 'd8f502d5beec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
