"""empty message

Revision ID: 7d8c53c131e1
Revises: bacea0d8d55b
Create Date: 2022-07-06 11:36:21.885638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d8c53c131e1'
down_revision = 'bacea0d8d55b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
