"""empty message

Revision ID: 92abc1baa23f
Revises: 
Create Date: 2022-07-01 13:36:52.350096

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '92abc1baa23f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('light')
    op.drop_table('media_routine_setting')
    op.drop_table('room')
    op.drop_table('trv')
    op.drop_table('routine')
    op.drop_table('trv_routine_setting')
    op.drop_table('media')
    op.drop_table('light_routine_setting')
    op.drop_table('home_user')
    op.drop_table('light_room')
    op.drop_table('home')
    op.drop_table('camera')
    op.drop_table('room_camera')
    op.drop_index('flyway_schema_history_s_idx', table_name='flyway_schema_history')
    op.drop_table('flyway_schema_history')
    op.drop_table('media_room')
    op.drop_table('room_alert')
    op.drop_table('room_user_entry')
    op.drop_table('routine_time_entries')
    op.drop_table('trv_room')
    op.drop_table('room_user_hierarchy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_user_hierarchy',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name='fk_user_hierarchy_room_room_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_hierarchy_user_user_id'),
    sa.PrimaryKeyConstraint('id', name='room_user_hierarchy_pkey')
    )
    op.create_table('trv_room',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('trv_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name='fk_trv_room_room_id'),
    sa.ForeignKeyConstraint(['trv_id'], ['trv.id'], name='fk_trv_room_trv_id'),
    sa.PrimaryKeyConstraint('id', name='trv_room_pkey')
    )
    op.create_table('routine_time_entries',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('routine_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time_entry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['routine_id'], ['routine.id'], name='fk_routine_time_entry_routine_id'),
    sa.PrimaryKeyConstraint('id', name='routine_time_entries_pkey')
    )
    op.create_table('room_user_entry',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name='fk_room_user_entry_room_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_room_user_entry_user_id'),
    sa.PrimaryKeyConstraint('id', name='room_user_entry_pkey')
    )
    op.create_table('room_alert',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('message', sa.VARCHAR(length=225), autoincrement=False, nullable=True),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name='fk_routine_alert_routine_id'),
    sa.PrimaryKeyConstraint('id', name='room_alert_pkey')
    )
    op.create_table('media_room',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('media_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name='fk_media_room_media_id'),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name='fk_media_room_room_id'),
    sa.PrimaryKeyConstraint('id', name='media_room_pkey')
    )
    op.create_table('flyway_schema_history',
    sa.Column('installed_rank', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('script', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('installed_by', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('installed_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('execution_time', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('installed_rank', name='flyway_schema_history_pk')
    )
    op.create_index('flyway_schema_history_s_idx', 'flyway_schema_history', ['success'], unique=False)
    op.create_table('room_camera',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('camera_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], name='fk_room_home_camera_id'),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name='fk_room_camera_room_id'),
    sa.PrimaryKeyConstraint('id', name='room_camera_pkey')
    )
    op.create_table('camera',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='camera_pkey')
    )
    op.create_table('home',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('home_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='home_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('light_room',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('light_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['light_id'], ['light.id'], name='fk_light_room_light_id'),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name='fk_light_room_room_id'),
    sa.PrimaryKeyConstraint('id', name='light_room_pkey')
    )
    op.create_table('home_user',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('home_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['home_id'], ['home.id'], name='fk_home_user_home_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_home_user_user_id'),
    sa.PrimaryKeyConstraint('id', name='home_user_pkey')
    )
    op.create_table('light_routine_setting',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('light_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('routine_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('brightness', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['light_id'], ['light.id'], name='fk_light_routine_setting_light_id'),
    sa.ForeignKeyConstraint(['routine_id'], ['routine.id'], name='fk_light_routine_setting_routine_id'),
    sa.PrimaryKeyConstraint('id', name='light_routine_setting_pkey')
    )
    op.create_table('media',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('is_playing', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='media_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('trv_routine_setting',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('trv_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('routine_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('temperature', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['routine_id'], ['routine.id'], name='fk_trv_routine_setting_routine_id'),
    sa.ForeignKeyConstraint(['trv_id'], ['trv.id'], name='fk_trv_routine_setting_trv_id'),
    sa.PrimaryKeyConstraint('id', name='trv_routine_setting_pkey')
    )
    op.create_table('routine',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name='fk_routine_room_room_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_routine_user_user_id'),
    sa.PrimaryKeyConstraint('id', name='routine_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('trv',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='trv_pkey')
    )
    op.create_table('room',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('room_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('home_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['home_id'], ['home.id'], name='fk_room_home_home_id'),
    sa.PrimaryKeyConstraint('id', name='room_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('media_routine_setting',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('media_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('routine_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('media_url', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name='fk_media_routine_setting_media_id'),
    sa.ForeignKeyConstraint(['routine_id'], ['routine.id'], name='fk_media_routine_setting_routine_id'),
    sa.PrimaryKeyConstraint('id', name='media_routine_setting_pkey')
    )
    op.create_table('light',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='light_pkey')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    # ### end Alembic commands ###
