"""empty message

Revision ID: 97db2b087b49
Revises: 74b7ba77d199
Create Date: 2022-07-06 19:40:56.642235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97db2b087b49'
down_revision = '74b7ba77d199'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
