"""empty message

Revision ID: bacea0d8d55b
Revises: 300d580bda3e
Create Date: 2022-07-06 11:35:16.425532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bacea0d8d55b'
down_revision = '300d580bda3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
