"""empty message

Revision ID: cf67c17ca4d5
Revises: 3a5df5e96c7f
Create Date: 2022-07-06 13:02:32.914859

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cf67c17ca4d5'
down_revision = '3a5df5e96c7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('routine', 'start_time',
               existing_type=postgresql.TIME(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('routine', 'end_time',
               existing_type=postgresql.TIME(),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('routine', 'end_time',
               existing_type=sa.String(length=50),
               type_=postgresql.TIME(),
               existing_nullable=True)
    op.alter_column('routine', 'start_time',
               existing_type=sa.String(length=50),
               type_=postgresql.TIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
