"""empty message

Revision ID: d8f502d5beec
Revises: 7d8c53c131e1
Create Date: 2022-07-06 12:43:16.155460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8f502d5beec'
down_revision = '7d8c53c131e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
