"""empty message

Revision ID: e170319d0fa6
Revises: c8d9d0608f18
Create Date: 2022-07-06 12:52:46.754702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e170319d0fa6'
down_revision = 'c8d9d0608f18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
